View(mtcars)
nrow(mtcars)
str(mtcars)
library(dplyr)
filter(mtcars, cyl ==4)
filter(mtcars, cyl>=6&mpg>20)
head(arrange(mtcars, wt))
head(mtcars)
head(select(mtcars, am, gear))
View(select(mtcars, am, gear))
head(mutate(mtcars, years="1974"))
head(mutate(mtcars, mpg_rank = rank(mpg)))
distinct(mtcars, cyl)
distinct(mtcars, gear)
distinct(mtcars, cyl, gear)
summarise(mtcars, cyl_mean = mean(cyl), cyl_min = min(cyl), cyl_max = max(cyl))
summarise(mtcars, mean(cyl), min(cyl), max(cyl))
gr_cyl <- group_by(mtcars, cyl)
View(gr_cyl)
summarise(gr_cyl, n())
arrange(mtcars,cyl)
sample_n(mtcars, 10)
sample_frac(mtcars, 0.2)
group_by(mtcars, cyl) %>% summarise(n())
mp_rank <- mutate(mtcars, mpg_rank = rank(mpg))
arrange(mp_rank, mpg_rank)
mutate(mtcars, mpg_rank = rank(mpg)) %>% arrange(mpg_rank)
